[package]
name = "parasailors"
version = "0.1.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
license = "MIT"
documentation = "https://dikaiosune.github.io/parasailors"
repository = "https://github.com/dikaiosune/parasailors"
readme = "README.md"
keywords = ["simd", "bioinformatics", "sequence alignment", "pairwise alignment"]

[dependencies]
libc = "0.2"
parasail_sys = { path = "parasail_sys" }
