[package]
name = "parasail-sys"
version = "0.1.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
links = "parasail"
build = "build.rs"
description = "Native bindings to the parasail pairwise genetic sequence alignment library."

[dependencies]
libc = "0.2"

[build-dependencies]
cmake = "0.1"
